import './style.css';

const defaultDevices = [
  { id: 'desk-01', name: 'Çalışma İstasyonu', model: 'Windows Desktop', status: 'online', install: 'Kurulum tamamlandı', lastSeen: 'Az önce', address: '192.168.1.24', protected: true, screen: true },
  { id: 'study-02', name: 'Ders Bilgisayarı', model: 'Windows Laptop', status: 'offline', install: 'Kurulum bekliyor', lastSeen: '2 saat önce', address: '192.168.1.31', protected: false, screen: false }
];

const state = {
  authenticated: sessionStorage.getItem('muntazam-auth') === 'true',
  route: location.hash.slice(1) || 'overview',
  selectedDevice: 'desk-01',
  devices: [],
  dataReady: false,
  navOpen: false
};

const icons = {
  grid: '<span class="icon icon-grid"></span>', devices: '<span class="icon icon-device"></span>', activity: '<span class="icon icon-activity"></span>', schedule: '<span class="icon icon-clock"></span>', settings: '<span class="icon icon-sliders"></span>', plus: '<span class="icon icon-plus"></span>', arrow: '<span class="icon icon-arrow"></span>', lock: '<span class="icon icon-lock"></span>', power: '<span class="icon icon-power"></span>'
};

async function api(path, options = {}) {
  const response = await fetch(`/api${path}`, { credentials: 'same-origin', headers: { 'Content-Type': 'application/json', ...options.headers }, ...options });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.error || 'İstek başarısız.');
  return body;
}
async function loadDevices() { state.devices = await api('/devices'); state.dataReady = true; }
function navigate(route) { location.hash = route; }
function device(id = state.selectedDevice) { return state.devices.find((item) => item.id === id) || state.devices[0]; }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char])); }

function loginView() {
  return `<main class="auth-shell"><div class="auth-grid"></div><section class="auth-card"><div class="brand brand-large"><div class="brand-mark"><img src="/iso.png" alt="" /></div><div><strong>MUNTAZAM</strong><span>CONTROL SYSTEM</span></div></div><div class="auth-copy"><p class="eyebrow">SECURE ACCESS / 01</p><h1>Kontrol alanına<br /><em>hoş geldin.</em></h1><p>Bağlı cihazlarını tek merkezden yönet. Tüm erişimler kayıt altında tutulur.</p></div><form id="login-form"><label for="login-password">Yönetici şifresi</label><div class="input-wrap">${icons.lock}<input id="login-password" type="password" autocomplete="current-password" placeholder="Şifreni gir" required /><button type="button" class="reveal" aria-label="Şifreyi göster">GÖR</button></div><button class="button button-primary button-wide" type="submit">Sisteme bağlan ${icons.arrow}</button><p class="form-note">Varsayılan erişim: 123123 · Ayarlardan değiştirilebilir</p></form><div class="auth-footer"><span class="status-dot"></span> Sistem hazır <span>v0.1 / LOCAL CONSOLE</span></div></section></main>`;
}

function shell(content, title, subtitle) {
  const nav = [['overview', icons.grid, 'Genel bakış'], ['devices', icons.devices, 'Cihazlar'], ['activity', icons.activity, 'Kayıtlar'], ['schedule', icons.schedule, 'Zamanlama'], ['settings', icons.settings, 'Ayarlar']];
  return `<div class="app-shell"><aside class="sidebar ${state.navOpen ? 'open' : ''}"><div class="sidebar-top"><div class="brand"><div class="brand-mark"><img src="/iso.png" alt="" /></div><div><strong>MUNTAZAM</strong><span>CONTROL SYSTEM</span></div></div><button class="mobile-close" id="close-nav">×</button></div><div class="console-label"><span class="status-dot"></span> LOCAL CONSOLE</div><nav>${nav.map(([route, icon, label]) => `<a class="nav-item ${state.route === route || (state.route.startsWith('device/') && route === 'devices') ? 'active' : ''}" href="#${route}">${icon}<span>${label}</span>${route === 'devices' ? `<b>${state.devices.length}</b>` : ''}</a>`).join('')}</nav><div class="sidebar-footer"><div class="mini-profile"><span class="avatar">M</span><span><strong>Yönetici</strong><small>Yetkili erişim</small></span><span class="presence"></span></div><button id="logout" class="logout">Oturumu kapat</button></div></aside><div class="main-area"><header class="topbar"><button class="mobile-menu" id="open-nav">MENU</button><div class="breadcrumbs"><span>CONSOLE</span><i>/</i><strong>${title.toUpperCase()}</strong></div><div class="top-actions"><span class="top-status"><span class="status-dot"></span> Sistem aktif</span><button class="top-icon" title="Bildirimler">${icons.activity}<i></i></button><div class="date-readout">${new Intl.DateTimeFormat('tr-TR', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date())}</div></div></header><main class="content"><div class="page-heading"><div><p class="eyebrow">${subtitle}</p><h1>${title}</h1></div>${state.route === 'devices' ? `<button class="button button-primary" id="add-device">${icons.plus} Cihaz ekle</button>` : ''}</div>${content}</main></div></div>`;
}

function overviewView() {
  const online = state.devices.filter((item) => item.status === 'online').length;
  return shell(`<section class="metrics"><div class="metric-card accent"><span>BAĞLI CİHAZLAR</span><strong>${state.devices.length.toString().padStart(2, '0')}</strong><small><b>${online}</b> çevrimiçi durumda</small><div class="metric-line"></div></div><div class="metric-card"><span>AKTİF OTURUMLAR</span><strong>01</strong><small><b class="green-text">+12%</b> son 24 saate göre</small><div class="sparkline"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div></div><div class="metric-card"><span>BEKLEYEN İŞLEMLER</span><strong>03</strong><small><b class="amber-text">İncele</b> işlem kuyruğunda</small><div class="metric-line amber"></div></div></section><section class="dashboard-grid"><div class="panel panel-devices"><div class="panel-head"><div><p class="eyebrow">DEVICE NETWORK</p><h2>Cihaz durumu</h2></div><a href="#devices" class="text-link">Tümünü gör ${icons.arrow}</a></div><div class="device-list">${state.devices.map(deviceRow).join('')}</div></div><div class="panel system-panel"><div class="panel-head"><div><p class="eyebrow">SYSTEM HEALTH</p><h2>İletişim durumu</h2></div><span class="live-label"><span class="status-dot"></span> LIVE</span></div><div class="health-ring"><div><strong>98</strong><span>%</span><small>STABİL</small></div></div><div class="health-stats"><span><i class="legend cyan"></i> Bağlantı <b>99.8%</b></span><span><i class="legend green"></i> Güvenlik <b>100%</b></span></div></div></section><section class="panel activity-panel"><div class="panel-head"><div><p class="eyebrow">RECENT EVENTS</p><h2>Son hareketler</h2></div><a href="#activity" class="text-link">Kayıtları aç ${icons.arrow}</a></div>${activityRows()}</section>`, 'Genel bakış', 'OPERASYON MERKEZİ / 01');
}

function deviceRow(item) { return `<a href="#device/${item.id}" class="device-row"><span class="device-glyph">${icons.devices}</span><span class="device-main"><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(item.model)} · ${item.address}</small></span><span class="device-install ${item.install.includes('bekliyor') ? 'pending' : ''}">${item.install}</span><span class="device-seen"><i class="status-dot ${item.status === 'offline' ? 'offline' : ''}"></i>${item.status === 'online' ? 'Çevrimiçi' : 'Çevrimdışı'}<small>${item.lastSeen}</small></span>${icons.arrow}</a>`; }
function activityRows() { return `<div class="activity-row"><span class="activity-symbol cyan">${icons.devices}</span><span><strong>Çalışma İstasyonu bağlandı</strong><small>Yeni bağlantı doğrulandı</small></span><time>02 dk önce</time></div><div class="activity-row"><span class="activity-symbol amber">${icons.schedule}</span><span><strong>Zamanlama güncellendi</strong><small>Ders Bilgisayarı / hafta içi</small></span><time>1 sa önce</time></div><div class="activity-row"><span class="activity-symbol green">${icons.settings}</span><span><strong>Güvenlik ayarları kaydedildi</strong><small>Yönetici tarafından</small></span><time>3 sa önce</time></div>`; }

function devicesView() { return shell(`<section class="panel devices-panel"><div class="device-table-head"><span>CİHAZ</span><span>DURUM</span><span>KURULUM</span><span>SON GÖRÜLME</span><span></span></div>${state.devices.map((item) => `<div class="device-table-row"><span class="device-main"><span class="device-glyph">${icons.devices}</span><span><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(item.model)} · ${item.address}</small></span></span><span><i class="status-dot ${item.status === 'offline' ? 'offline' : ''}"></i>${item.status === 'online' ? 'Çevrimiçi' : 'Çevrimdışı'}</span><span class="device-install ${item.install.includes('bekliyor') ? 'pending' : ''}">${item.install}</span><span>${item.lastSeen}</span><a class="table-arrow" href="#device/${item.id}">${icons.arrow}</a></div>`).join('')}</section><section class="pairing-banner"><div><p class="eyebrow">NEW ENDPOINT</p><h2>Yeni bir cihaz bağla</h2><p>Güvenli bir eşleştirme anahtarı üret ve cihaz uygulamasında kullan.</p></div><button class="button button-outline" id="add-device">${icons.plus} Cihaz ekle</button></section>`, 'Cihazlar', 'ENDPOINT YÖNETİMİ / 02'); }

function deviceDetailView(id) { const item = device(id); if (!item) return devicesView(); state.selectedDevice = id; return shell(`<div class="detail-back"><a href="#devices">${icons.arrow} Cihaz listesine dön</a></div><section class="detail-header"><div class="detail-device-title"><span class="device-glyph large">${icons.devices}</span><div><p class="eyebrow">ENDPOINT / ${item.id.toUpperCase()}</p><h1>${escapeHtml(item.name)}</h1><span><i class="status-dot ${item.status === 'offline' ? 'offline' : ''}"></i> ${item.status === 'online' ? 'Çevrimiçi' : 'Çevrimdışı'} · ${item.lastSeen}</span></div></div><div class="detail-actions"><button class="button button-outline" data-action="edit">Düzenle</button><button class="button button-danger" data-action="lock">${icons.lock} ${item.status === 'online' ? 'Ekranı kilitle' : 'Bağlantı bekleniyor'}</button></div></section><section class="live-grid"><div class="panel screen-panel"><div class="panel-head"><div><p class="eyebrow">LIVE VIEW / USER CONSENT REQUIRED</p><h2>Canlı ekran bağlantısı</h2></div><span class="live-label"><span class="status-dot"></span> ${item.screen ? 'READY' : 'OFFLINE'}</span></div><div class="screen-preview ${item.screen ? '' : 'screen-off'}"><div class="screen-noise"></div><div class="screen-center">${item.screen ? `<span class="screen-cursor"></span><strong>CANLI EKRAN</strong><small>Bağlantı güvenli şekilde şifrelendi</small>` : `<span class="screen-off-icon">${icons.power}</span><strong>CIHAZ ÇEVRİMDIŞI</strong><small>Cihaz uygulaması bağlantı bekliyor</small>`}</div><div class="screen-bar"><span>1280 × 720</span><span>Gecikme 42 ms</span><span>Şifreli bağlantı</span></div></div></div><div class="panel command-panel"><div class="panel-head"><div><p class="eyebrow">QUICK COMMANDS</p><h2>İşlemler</h2></div></div><button class="command-button" data-action="lock"><span>${icons.lock}</span><span><strong>Ekranı kilitle</strong><small>Bağlantıyı açık tut</small></span>${icons.arrow}</button><button class="command-button" data-action="restart"><span>${icons.power}</span><span><strong>Yeniden başlat</strong><small>Onay gerektirir</small></span>${icons.arrow}</button><button class="command-button" data-action="safe"><span>${icons.settings}</span><span><strong>Güvenli moda al</strong><small>İzinleri sınırla</small></span>${icons.arrow}</button><div class="command-warning">${icons.lock}<span>Uzaktan komutlar cihazda görünür şekilde bildirilir.</span></div></div></section>`, 'Cihaz detayı', 'ENDPOINT KONTROLÜ / 03'); }

function scheduleView() { return shell(`<section class="schedule-layout"><div class="panel schedule-panel"><div class="panel-head"><div><p class="eyebrow">ACTIVE RULES</p><h2>Çalışma planı</h2></div><button class="button button-primary" id="new-rule">${icons.plus} Kural ekle</button></div><div class="rule-row"><span class="rule-icon">${icons.schedule}</span><span><strong>Hafta içi gece modu</strong><small>Pazartesi – Cuma</small></span><b>22:00 — 07:00</b><label class="switch"><input type="checkbox" checked /><span></span></label><button class="row-more">•••</button></div><div class="rule-row"><span class="rule-icon amber-bg">${icons.schedule}</span><span><strong>Hafta sonu sınırı</strong><small>Cumartesi – Pazar</small></span><b>23:30 — 08:30</b><label class="switch"><input type="checkbox" checked /><span></span></label><button class="row-more">•••</button></div><div class="rule-row muted-row"><span class="rule-icon">${icons.schedule}</span><span><strong>Özel program</strong><small>Henüz cihaz seçilmedi</small></span><b>--:-- — --:--</b><label class="switch"><input type="checkbox" /><span></span></label><button class="row-more">•••</button></div></div><div class="panel schedule-info"><p class="eyebrow">SCHEDULE ENGINE</p><h2>Otomatik kontrol</h2><p>Aktif kurallar cihaz uygulaması çevrimiçi olduğunda otomatik olarak uygulanır. Cihaz bağlantısı kesilirse son kural yerel olarak korunur.</p><div class="info-line"><span class="status-dot"></span><span>Motor çalışıyor</span><b>SYNCED</b></div></div></section>`, 'Zamanlama', 'POLICY ENGINE / 04'); }

function activityView() { return shell(`<section class="panel full-activity"><div class="panel-head"><div><p class="eyebrow">AUDIT TRAIL</p><h2>İşlem kayıtları</h2></div><button class="button button-outline">Dışa aktar ${icons.arrow}</button></div><div class="filter-line"><button class="filter active">Tümü</button><button class="filter">Bağlantılar</button><button class="filter">Komutlar</button><button class="filter">Ayarlar</button><span class="filter-date">Son 7 gün ${icons.schedule}</span></div><div class="audit-row"><time>BUGÜN<small>14:32</small></time><span class="activity-symbol cyan">${icons.devices}</span><span><strong>Çalışma İstasyonu çevrimiçi oldu</strong><small>192.168.1.24 üzerinden güvenli bağlantı</small></span><b class="audit-ok">BAŞARILI</b></div><div class="audit-row"><time>BUGÜN<small>13:08</small></time><span class="activity-symbol amber">${icons.lock}</span><span><strong>Ekran kilitleme komutu gönderildi</strong><small>Çalışma İstasyonu / yönetici</small></span><b class="audit-ok">BAŞARILI</b></div><div class="audit-row"><time>DÜN<small>22:00</small></time><span class="activity-symbol green">${icons.schedule}</span><span><strong>Gece modu kuralı uygulandı</strong><small>2 cihaza uygulandı</small></span><b class="audit-ok">BAŞARILI</b></div><div class="audit-row"><time>DÜN<small>18:44</small></time><span class="activity-symbol cyan">${icons.settings}</span><span><strong>Endpoint ayarları güncellendi</strong><small>Çalışma İstasyonu / cihaz adı</small></span><b class="audit-ok">BAŞARILI</b></div></div>`, 'Kayıtlar', 'AUDIT TRAIL / 05'); }

function settingsView() { return shell(`<section class="settings-layout"><div class="panel settings-panel"><div class="panel-head"><div><p class="eyebrow">ACCESS CONTROL</p><h2>Giriş ayarları</h2></div></div><form id="settings-form" class="settings-form"><label>Yönetici şifresi<small>Panel girişinde kullanılan şifreyi değiştir.</small><div class="input-wrap"><input name="newPassword" type="password" minlength="6" placeholder="Yeni şifre" required /><button type="button" class="reveal">GÖR</button></div></label><label>Oturum süresi<small>İnaktiflik sonrası otomatik çıkış.</small><select><option>30 dakika</option><option>1 saat</option><option>4 saat</option></select></label><button class="button button-primary" type="submit">Ayarları kaydet ${icons.arrow}</button><span id="settings-message" class="success-message"></span></form></div><div class="panel settings-panel"><div class="panel-head"><div><p class="eyebrow">CONNECTION POLICY</p><h2>Bağlantı politikası</h2></div></div><div class="setting-toggle"><span><strong>Yeni cihaz doğrulaması</strong><small>Her yeni bağlantı için tek kullanımlık anahtar iste.</small></span><label class="switch"><input type="checkbox" checked /><span></span></label></div><div class="setting-toggle"><span><strong>Komut bildirimleri</strong><small>Uzaktan işlemleri panelde ve cihazda görünür kıl.</small></span><label class="switch"><input type="checkbox" checked /><span></span></label></div><div class="setting-toggle"><span><strong>Audit log koruması</strong><small>İşlem kayıtlarının silinmesini engelle.</small></span><label class="switch"><input type="checkbox" checked /><span></span></label></div></div></section>`, 'Ayarlar', 'SYSTEM CONFIG / 06'); }

function addDeviceModal() { return `<div class="modal-backdrop" id="device-modal"><div class="modal"><button class="modal-close" id="close-modal">×</button><p class="eyebrow">NEW ENDPOINT / PAIRING</p><h2>Cihaz bağla</h2><p class="modal-copy">Bu tek kullanımlık anahtarı Muntazam cihaz uygulamasına gir. Ardından cihaz adını belirleyip bağlantıyı tamamla.</p><div class="pair-key">MNT-${crypto.randomUUID().replaceAll('-', '').slice(0, 20).toUpperCase()}<button id="copy-key">KOPYALA</button></div><form id="device-form"><label>Cihaz adı<input name="name" placeholder="Örn. Çalışma odası" required /></label><label class="check-label"><input name="protected" type="checkbox" checked /> Cihaz işlemlerini parola ile koru</label><div class="modal-actions"><button type="button" class="button button-outline" id="cancel-modal">İptal</button><button class="button button-primary" type="submit">Eşleştirmeyi tamamla ${icons.arrow}</button></div></form></div></div>`; }

function render() { if (!state.authenticated) { document.querySelector('#app').innerHTML = loginView(); bindLogin(); return; } let view = overviewView(); if (state.route === 'devices') view = devicesView(); else if (state.route.startsWith('device/')) view = deviceDetailView(state.route.split('/')[1]); else if (state.route === 'activity') view = activityView(); else if (state.route === 'schedule') view = scheduleView(); else if (state.route === 'settings') view = settingsView(); document.querySelector('#app').innerHTML = view; bindShell(); }
function bindLogin() { const form = document.querySelector('#login-form'); form.addEventListener('submit', async (event) => { event.preventDefault(); try { await api('/auth/login', { method: 'POST', body: JSON.stringify({ password: form.querySelector('input').value }) }); await loadDevices(); state.authenticated = true; sessionStorage.setItem('muntazam-auth', 'true'); render(); } catch { form.classList.add('shake'); setTimeout(() => form.classList.remove('shake'), 500); form.querySelector('input').focus(); } }); document.querySelector('.reveal').addEventListener('click', (event) => { const input = form.querySelector('input'); input.type = input.type === 'password' ? 'text' : 'password'; event.currentTarget.textContent = input.type === 'password' ? 'GÖR' : 'GİZLE'; }); }
function bindShell() { document.querySelector('#logout')?.addEventListener('click', async () => { await api('/auth/logout', { method: 'POST' }); state.authenticated = false; state.dataReady = false; state.devices = []; sessionStorage.removeItem('muntazam-auth'); render(); }); document.querySelector('#open-nav')?.addEventListener('click', () => document.querySelector('.sidebar').classList.add('open')); document.querySelector('#close-nav')?.addEventListener('click', () => document.querySelector('.sidebar').classList.remove('open')); document.querySelector('#add-device')?.addEventListener('click', () => { document.body.insertAdjacentHTML('beforeend', addDeviceModal()); bindModal(); }); document.querySelectorAll('[data-action]').forEach((button) => button.addEventListener('click', async () => { const action = button.dataset.action; const command = { lock: 'lock', restart: 'restart', safe: 'safe-mode' }[action]; if (command) await api(`/devices/${state.selectedDevice}/commands`, { method: 'POST', body: JSON.stringify({ command }) }); const labels = { lock: 'Ekran kilitleme komutu hazırlandı.', restart: 'Yeniden başlatma için cihaz onayı bekleniyor.', safe: 'Güvenli mod komutu hazırlandı.', edit: 'Cihaz düzenleme ekranı sonraki adımda açılacak.' }; alert(labels[action] || 'İşlem hazırlandı.'); })); const settings = document.querySelector('#settings-form'); settings?.addEventListener('submit', async (event) => { event.preventDefault(); const value = new FormData(settings).get('newPassword'); try { await api('/settings/password', { method: 'PATCH', body: JSON.stringify({ password: value }) }); document.querySelector('#settings-message').textContent = 'Şifre güncellendi.'; settings.reset(); } catch (error) { document.querySelector('#settings-message').textContent = error.message; } }); document.querySelectorAll('.reveal').forEach((button) => button.addEventListener('click', () => { const input = button.parentElement.querySelector('input'); input.type = input.type === 'password' ? 'text' : 'password'; button.textContent = input.type === 'password' ? 'GÖR' : 'GİZLE'; })); }
function bindModal() { const modal = document.querySelector('#device-modal'); const close = () => modal.remove(); document.querySelector('#close-modal').addEventListener('click', close); document.querySelector('#cancel-modal').addEventListener('click', close); document.querySelector('#copy-key').addEventListener('click', (event) => { navigator.clipboard?.writeText(document.querySelector('.pair-key').firstChild.textContent); event.currentTarget.textContent = 'KOPYALANDI'; }); document.querySelector('#device-form').addEventListener('submit', async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); try { const newDevice = await api('/devices', { method: 'POST', body: JSON.stringify({ name: data.get('name'), protected: data.get('protected') === 'on' }) }); state.devices.push(newDevice); close(); render(); } catch (error) { alert(error.message); } }); }
async function bootstrap() { if (!state.authenticated) return render(); try { await loadDevices(); render(); } catch { state.authenticated = false; sessionStorage.removeItem('muntazam-auth'); render(); } }
window.addEventListener('hashchange', () => { state.route = location.hash.slice(1) || 'overview'; render(); }); bootstrap();
